source F:\Dropbox\dbSchema\Project.SQL
source F:\Dropbox\dbSchema\Class.SQL
source F:\Dropbox\dbSchema\Interface.SQL
source F:\Dropbox\dbSchema\InterfaceExtendRelation.SQL
source F:\Dropbox\dbSchema\ClassInterfaceRelation.SQL
source F:\Dropbox\dbSchema\Field.SQL
source F:\Dropbox\dbSchema\Method.SQL
source F:\Dropbox\dbSchema\MethodParameter.SQL
source F:\Dropbox\dbSchema\CloneSet.SQL
source F:\Dropbox\dbSchema\CloneInstance.SQL
source F:\Dropbox\dbSchema\Variable.SQL
source F:\Dropbox\dbSchema\Constant.SQL
source F:\Dropbox\dbSchema\CommonPartAccess.SQL
source F:\Dropbox\dbSchema\CommonPartCall.SQL
source F:\Dropbox\dbSchema\CommonPartUseType.SQL
source F:\Dropbox\dbSchema\DiffPartAccess.SQL
source F:\Dropbox\dbSchema\DiffPartCall.SQL
source F:\Dropbox\dbSchema\DiffPartUseType.SQL
source F:\Dropbox\dbSchema\DiffPartKeyword.SQL
